[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.1"

[[constraint]]
  branch = "master"
  name = "github.com/jacobsa/fuse"

[[constraint]]
  name = "github.com/syndtr/goleveldb"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "gopkg.in/kothar/go-backblaze.v0"

[prune]
  go-tests = true
  unused-packages = true
