[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.20.20"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.1"

[[constraint]]
  branch = "master"
  name = "github.com/jacobsa/fuse"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.10.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "gopkg.in/kothar/go-backblaze.v0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
